/**
 * Fund page copy, EN / FR. Wording reused from nymbus-decks src/v2/content.ts (kpis, perf, strategies…)
 * and from the current site's fund pages / footer disclaimer. Pure data.
 */
import type { DocType, Period } from "../../lib/data/types.ts";

export type L = { en: string; fr: string };
const l = (en: string, fr: string): L => ({ en, fr });

export const T = {
  sections: {
    overview: l("overview", "aperçu"),
    performance: l("performance", "performance"),
    growth: l("growth", "croissance"),
    calendar: l("calendar years", "années civiles"),
    monthly: l("monthly", "mensuel"),
    risk: l("risk", "risque"),
    portfolio: l("portfolio", "portefeuille"),
    facts: l("fund facts", "faits sur le fonds"),
    documents: l("documents", "documents"),
    disclosure: l("disclosure", "mentions"),
  },
  nav: { funds: l("strategies", "stratégies"), sections: l("on this page", "sur cette page") },
  sample: {
    ribbon: l("sample data", "données fictives"),
    note: l("illustrative figures only, not actual performance", "chiffres illustratifs seulement, pas des rendements réels"),
  },
  hero: {
    net: l("net annualized return", "rendement annualisé net"),
    netCum: l("net return", "rendement net"),
    gross: l("gross annualized return", "rendement annualisé brut"),
    grossCum: l("gross return", "rendement brut"),
    since: l("since inception", "depuis la création"),
    asOf: l("as of", "au"),
    va: l("value-added vs benchmark", "valeur ajoutée vs indice de référence"),
    nav: l("net asset value", "valeur liquidative"),
    class: l("class", "classe"),
    vehicleFund: l("investment fund", "fonds d’investissement"),
    vehicleStrategy: l("managed accounts", "comptes gérés"),
    inception: l("solution inception", "création de la solution"),
    fundserv: l("fundserv", "fundserv"),
    risk: l("risk level", "niveau de risque"),
    levels: [l("low", "faible"), l("low to medium", "faible à moyen"), l("medium", "moyen"), l("medium to high", "moyen à élevé"), l("high", "élevé")],
    basisNet: l("net of fees", "net de frais"),
    basisGross: l("gross of fees · managed accounts, not a fund", "brut de frais · comptes gérés, pas un fonds"),
    grossNote: l(
      "Returns shown for this strategy are gross of fees and represent managed accounts; they are not the returns of an investment fund. Client returns are reduced by management fees and other expenses, and vary by account.",
      "Les rendements présentés pour cette stratégie sont bruts de frais et représentent des comptes gérés; il ne s’agit pas des rendements d’un fonds d’investissement. Les rendements des clients sont réduits par les frais de gestion et autres frais, et varient d’un compte à l’autre.",
    ),
    explore: l("explore the numbers", "explorer les chiffres"),
    day: l("vs previous valuation day", "vs jour d’évaluation précédent"),
  },
  trailing: {
    kicker: l("performance", "performance"),
    title: l("trailing returns", "rendements cumulatifs"),
    fund: l("fund", "fonds"),
    strategy: l("strategy", "stratégie"),
    index: l("index", "indice"),
    va: l("value added", "valeur ajoutée"),
    annualized: l("Periods of 2 years and more, and since inception, are annualized.", "Les périodes de 2 ans et plus, ainsi que depuis la création, sont annualisées."),
    table: l("show the numbers", "afficher les chiffres"),
    period: l("period", "période"),
    periods: {
      "1M": l("1M", "1 m"), "3M": l("3M", "3 m"), YTD: l("YTD", "AAJ"), "1Y": l("1Y", "1 an"), "2Y": l("2Y", "2 ans"), "3Y": l("3Y", "3 ans"),
      "5Y": l("5Y", "5 ans"), "10Y": l("10Y", "10 ans"), SI: l("SI", "DC"),
    } as Record<Period, L>,
    periodsLong: {
      "1M": l("1 month", "1 mois"), "3M": l("3 months", "3 mois"), YTD: l("year to date", "depuis le début de l’année"), "1Y": l("1 year", "1 an"),
      "2Y": l("2 years", "2 ans"), "3Y": l("3 years", "3 ans"), "5Y": l("5 years", "5 ans"), "10Y": l("10 years", "10 ans"), SI: l("since inception", "depuis la création"),
    } as Record<Period, L>,
  },
  growth: {
    kicker: l("growth", "croissance"),
    title: l("growth of $10,000", "croissance de 10 000 $"),
    lead: l("a hypothetical $10,000 investment, distributions reinvested", "un placement hypothétique de 10 000 $, distributions réinvesties"),
    range: l("period", "période"),
    ranges: { "1Y": l("1Y", "1 an"), "3Y": l("3Y", "3 ans"), "5Y": l("5Y", "5 ans"), SI: l("since inception", "depuis la création") },
    rebased: l("rebased to $10,000 at the start of the period", "ramené à 10 000 $ au début de la période"),
    keys: l("use the arrow keys to move through the months", "utilisez les flèches pour parcourir les mois"),
  },
  calendar: {
    kicker: l("calendar years", "années civiles"),
    title: l("year by year", "année après année"),
    ytd: l("ytd", "aaj"),
    partial: l("partial year", "année partielle"),
    year: l("year", "année"),
  },
  heatmap: {
    kicker: l("monthly returns", "rendements mensuels"),
    title: l("every month, since inception", "chaque mois, depuis la création"),
    year: l("year", "année"),
    total: l("year", "année"),
    legendNeg: l("negative", "négatif"),
    legendPos: l("positive", "positif"),
  },
  risk: {
    kicker: l("risk", "risque"),
    title: l("the ride matters", "le parcours compte"),
    windows: { SI: l("since inception", "depuis la création"), "3Y": l("3 years", "3 ans") },
    annReturn: l("annualized return", "rendement annualisé"),
    annVol: l("volatility", "volatilité"),
    downsideDev: l("downside deviation", "écart baissier"),
    sharpe: l("sharpe ratio", "ratio de Sharpe"),
    sortino: l("sortino ratio", "ratio de Sortino"),
    maxDrawdown: l("max drawdown", "recul maximal"),
    positiveMonths: l("positive months", "mois positifs"),
    bestMonth: l("best month", "meilleur mois"),
    worstMonth: l("worst month", "pire mois"),
    annualized: l("annualized, from monthly returns", "annualisé, à partir des rendements mensuels"),
  },
  portfolio: {
    kicker: l("portfolio", "portefeuille"),
    title: l("inside the portfolio", "au cœur du portefeuille"),
    factsheet: l("from the monthly factsheet of", "selon la fiche mensuelle de"),
    index: l("index", "indice"),
    fund: l("fund", "fonds"),
    breakdowns: {
      credit: l("credit ratings", "cotes de crédit"),
      sectors: l("sectors", "secteurs"),
      curve: l("term structure", "structure des échéances"),
      country: l("countries", "pays"),
      assetClass: l("strategy allocation", "répartition des stratégies"),
    },
    holdings: l("top 10 holdings", "10 principaux titres"),
    weight: l("weight", "poids"),
    esg: l("sustainability metrics", "indicateurs de durabilité"),
    esgLead: l("the portfolio vs its index", "le portefeuille vs son indice"),
    characteristics: l("characteristics", "caractéristiques"),
  },
  facts: {
    kicker: l("fund facts", "faits sur le fonds"),
    title: l("the essentials", "l’essentiel"),
    classes: l("classes", "catégories de parts"),
    fundserv: l("fundserv", "fundserv"),
    class: l("class", "catégorie"),
    currency: l("currency", "devise"),
    nav: l("nav", "vl"),
    change: l("change", "variation"),
    date: l("date", "date"),
    headline: l("headline class", "catégorie de référence"),
    inception: l("inception", "création"),
    benchmark: l("benchmark", "indice de référence"),
    managementFee: l("management fee", "frais de gestion"),
    performanceFee: l("performance fee", "frais de performance"),
    mer: l("MER", "RFG"),
    minInvestment: l("minimum investment", "placement minimal"),
    distributions: l("distributions", "distributions"),
    managers: l("portfolio managers", "gestionnaires de portefeuille"),
    aum: l("assets under management", "actif sous gestion"),
    vehicle: l("vehicle", "véhicule"),
    assetClass: l("asset class", "classe d’actifs"),
    risk: l("risk rating", "cote de risque"),
    asOf: l("as of", "au"),
    objective: l("objective", "objectif"),
  },
  docs: {
    kicker: l("documents", "documents"),
    title: l("read the details", "lire les détails"),
    firm: l("firm", "firme"),
    download: l("download", "télécharger"),
    types: {
      factsheet: l("factsheets", "fiches mensuelles"),
      "fund-facts": l("fund facts", "aperçus du fonds"),
      prospectus: l("offering documents", "documents de placement"),
      "annual-report": l("annual reports", "rapports annuels"),
      "interim-report": l("interim reports", "rapports intermédiaires"),
      mrfp: l("management reports of fund performance", "rapports de la direction sur le rendement du fonds"),
      commentary: l("commentaries", "commentaires"),
      presentation: l("presentations", "présentations"),
      esg: l("sustainability", "durabilité"),
      other: l("other", "autres"),
    } as Record<DocType, L>,
  },
  disclosure: {
    kicker: l("important information", "renseignements importants"),
    title: l("disclosure", "mentions importantes"),
    net: l(
      "Returns are net of fees for the class shown, in Canadian dollars, and assume the reinvestment of all distributions.",
      "Les rendements sont nets de frais pour la catégorie présentée, en dollars canadiens, et supposent le réinvestissement de toutes les distributions.",
    ),
    standard: l(
      "Commissions, trailing commissions, management fees and expenses all may be associated with investments in investment funds. Please read the offering documents before investing. Investment funds are not guaranteed, their values change frequently and past performance may not be repeated. The indicated rates of return are the historical annual compounded total returns including changes in unit value and reinvestment of all distributions, and do not take into account sales, redemption, distribution or optional charges or income taxes payable by any securityholder that would have reduced returns.",
      "Les placements dans les fonds d’investissement peuvent donner lieu à des commissions, des commissions de suivi, des frais de gestion et d’autres frais. Veuillez lire les documents de placement avant d’investir. Les fonds d’investissement ne sont pas garantis, leur valeur fluctue fréquemment et le rendement passé pourrait ne pas se reproduire. Les taux de rendement indiqués sont les rendements totaux annuels composés historiques, compte tenu des fluctuations de la valeur des parts et du réinvestissement de toutes les distributions, et ne tiennent pas compte des frais de vente, de rachat, de distribution ou des frais optionnels ni des impôts sur le revenu payables par le porteur, lesquels auraient pour effet de réduire le rendement.",
    ),
    index: l(
      "Indices are shown for comparison only; they are unmanaged, bear no fees and cannot be invested in directly.",
      "Les indices ne sont présentés qu’à titre de comparaison; ils ne sont pas gérés, n’assument aucuns frais et on ne peut y investir directement.",
    ),
    general: l(
      "This website is for informational purposes only and does not constitute investment advice, an offer to sell, or a solicitation to buy any security. Past performance is not indicative of future results.",
      "Ce site Web est fourni à titre informatif uniquement et ne constitue pas un conseil en investissement, une offre de vente ou une sollicitation d’achat d’un titre quelconque. Le rendement passé n’est pas indicatif des rendements futurs.",
    ),
    provenance: l("Updated daily from Nymbus’ data platform", "Mis à jour quotidiennement à partir de la plateforme de données de Nymbus"),
    provenanceFactsheet: l("portfolio data from the monthly factsheet of", "données de portefeuille selon la fiche mensuelle de"),
    perfAsOf: l("performance as of", "rendements au"),
    navAsOf: l("net asset values as of", "valeurs liquidatives au"),
    aumAsOf: l("assets as of", "actif au"),
    sample: l(
      "The figures on this page are illustrative sample data used while the data platform is not connected. They are not the actual returns of the fund.",
      "Les chiffres de cette page sont des données fictives utilisées tant que la plateforme de données n’est pas branchée. Il ne s’agit pas des rendements réels du fonds.",
    ),
  },
  misc: {
    noData: l("figures will appear here once published", "les chiffres apparaîtront ici une fois publiés"),
    fund: l("fund", "fonds"),
    index: l("index", "indice"),
  },
} as const;

/** Pick the string of the current language. */
export const tr = (x: L | undefined | null, lang: "en" | "fr") => (x ? x[lang] || x.en : "");
