/**
 * Fund page copy, EN / FR. Wording reused from nymbus-decks src/v2/content.ts (kpis, perf, strategies…)
 * and from the current site's fund pages / footer disclaimer. Pure data.
 */
import type { DocType, Period } from "../../lib/data/types.ts";
import { DISC } from "../../content/disclaimers.ts";

export type L = { en: string; fr: string };
const l = (en: string, fr: string): L => ({ en, fr });

export const T = {
  sections: {
    overview: l("overview", "aperçu"),
    performance: l("performance", "performance"),
    growth: l("growth", "croissance"),
    calendar: l("calendar years", "années civiles"),
    monthly: l("monthly", "mensuel"),
    risk: l("risk", "risque"),
    portfolio: l("portfolio", "portefeuille"),
    facts: l("fund facts", "faits sur le fonds"),
    documents: l("documents", "documents"),
    disclosure: l("disclosure", "mentions"),
  },
  nav: { funds: l("strategies", "stratégies"), sections: l("on this page", "sur cette page") },
  sample: {
    ribbon: l("sample data", "données fictives"),
    note: l("illustrative figures only, not actual performance", "chiffres illustratifs seulement, pas des rendements réels"),
  },
  hero: {
    net: l("net annualized return", "rendement annualisé net"),
    netCum: l("net return", "rendement net"),
    gross: l("gross annualized return", "rendement annualisé brut"),
    grossCum: l("gross return", "rendement brut"),
    since: l("since inception", "depuis la création"),
    asOf: l("as of", "au"),
    va: l("value-added vs benchmark", "valeur ajoutée vs indice de référence"),
    nav: l("net asset value", "valeur liquidative"),
    class: l("class", "classe"),
    vehicleFund: l("investment fund", "fonds d’investissement"),
    vehicleStrategy: l("managed accounts", "comptes gérés"),
    inception: l("solution inception", "création de la solution"),
    fundserv: l("fundserv", "fundserv"),
    risk: l("risk level", "niveau de risque"),
    levels: [l("low", "faible"), l("low to medium", "faible à moyen"), l("medium", "moyen"), l("medium to high", "moyen à élevé"), l("high", "élevé")],
    basisNet: l("net of fees", "net de frais"),
    basisGross: l("gross of fees · managed accounts, not a fund", "brut de frais · comptes gérés, pas un fonds"),
    // regulatory text: src/content/disclaimers.ts (compliance review)
    grossNote: DISC.gmvGross,
    explore: l("explore the numbers", "explorer les chiffres"),
    inLine: l("in line with benchmark", "en ligne avec l’indice"),
    noChange: l("no daily change published", "aucune variation quotidienne publiée"),
    day: l("vs previous valuation day", "vs jour d’évaluation précédent"),
  },
  trailing: {
    kicker: l("performance", "performance"),
    title: l("trailing returns", "rendements cumulatifs"),
    fund: l("fund", "fonds"),
    strategy: l("strategy", "stratégie"),
    index: l("index", "indice"),
    va: l("value added", "valeur ajoutée"),
    annualized: l("Periods of 2 years and more, and since inception, are annualized.", "Les périodes de 2 ans et plus, ainsi que depuis la création, sont annualisées."),
    table: l("show the numbers", "afficher les chiffres"),
    period: l("period", "période"),
    periods: {
      "1M": l("1M", "1 m"), "3M": l("3M", "3 m"), YTD: l("YTD", "AAJ"), "1Y": l("1Y", "1 an"), "2Y": l("2Y", "2 ans"), "3Y": l("3Y", "3 ans"),
      "5Y": l("5Y", "5 ans"), "10Y": l("10Y", "10 ans"), SI: l("SI", "DC"),
    } as Record<Period, L>,
    periodsLong: {
      "1M": l("1 month", "1 mois"), "3M": l("3 months", "3 mois"), YTD: l("year to date", "depuis le début de l’année"), "1Y": l("1 year", "1 an"),
      "2Y": l("2 years", "2 ans"), "3Y": l("3 years", "3 ans"), "5Y": l("5 years", "5 ans"), "10Y": l("10 years", "10 ans"), SI: l("since inception", "depuis la création"),
    } as Record<Period, L>,
  },
  growth: {
    kicker: l("growth", "croissance"),
    title: l("growth of $10,000", "croissance de 10 000 $"),
    lead: l("a hypothetical $10,000 investment, distributions reinvested", "un placement hypothétique de 10 000 $, distributions réinvesties"),
    range: l("period", "période"),
    ranges: { "1Y": l("1Y", "1 an"), "3Y": l("3Y", "3 ans"), "5Y": l("5Y", "5 ans"), SI: l("since inception", "depuis la création") },
    rebased: l("rebased to $10,000 at the start of the period", "ramené à 10 000 $ au début de la période"),
    keys: l("use the arrow keys to move through the months", "utilisez les flèches pour parcourir les mois"),
  },
  calendar: {
    kicker: l("calendar years", "années civiles"),
    title: l("year by year", "année après année"),
    ytd: l("ytd", "aaj"),
    partial: l("partial year", "année partielle"),
    year: l("year", "année"),
  },
  heatmap: {
    kicker: l("monthly returns", "rendements mensuels"),
    title: l("every month, since inception", "chaque mois, depuis la création"),
    year: l("year", "année"),
    total: l("year", "année"),
    legendNeg: l("negative", "négatif"),
    legendPos: l("positive", "positif"),
  },
  risk: {
    kicker: l("risk", "risque"),
    title: l("the ride matters", "le parcours compte"),
    windows: { SI: l("since inception", "depuis la création"), "3Y": l("3 years", "3 ans") },
    annReturn: l("annualized return", "rendement annualisé"),
    annVol: l("volatility", "volatilité"),
    downsideDev: l("downside deviation", "écart baissier"),
    sharpe: l("sharpe ratio", "ratio de Sharpe"),
    sortino: l("sortino ratio", "ratio de Sortino"),
    maxDrawdown: l("max drawdown", "recul maximal"),
    positiveMonths: l("positive months", "mois positifs"),
    bestMonth: l("best month", "meilleur mois"),
    worstMonth: l("worst month", "pire mois"),
    annualized: l("annualized, from monthly returns", "annualisé, à partir des rendements mensuels"),
  },
  portfolio: {
    kicker: l("portfolio", "portefeuille"),
    title: l("inside the portfolio", "au cœur du portefeuille"),
    factsheet: l("from the monthly factsheet of", "selon la fiche mensuelle de"),
    index: l("index", "indice"),
    fund: l("fund", "fonds"),
    breakdowns: {
      credit: l("credit ratings", "cotes de crédit"),
      sectors: l("sectors", "secteurs"),
      curve: l("term structure", "structure des échéances"),
      country: l("countries", "pays"),
      assetClass: l("strategy allocation", "répartition des stratégies"),
    },
    holdings: l("top 10 holdings", "10 principaux titres"),
    weight: l("weight", "poids"),
    esg: l("sustainability metrics", "indicateurs de durabilité"),
    esgLead: l("the portfolio vs its index", "le portefeuille vs son indice"),
    characteristics: l("characteristics", "caractéristiques"),
  },
  facts: {
    kicker: l("fund facts", "faits sur le fonds"),
    title: l("the essentials", "l’essentiel"),
    classes: l("classes", "catégories de parts"),
    fundserv: l("fundserv", "fundserv"),
    class: l("class", "catégorie"),
    currency: l("currency", "devise"),
    nav: l("nav", "vl"),
    change: l("change", "variation"),
    date: l("date", "date"),
    headline: l("headline class", "catégorie de référence"),
    inception: l("inception", "création"),
    benchmark: l("benchmark", "indice de référence"),
    managementFee: l("management fee", "frais de gestion"),
    performanceFee: l("performance fee", "frais de performance"),
    mer: l("MER", "RFG"),
    minInvestment: l("minimum investment", "placement minimal"),
    distributions: l("distributions", "distributions"),
    managers: l("portfolio managers", "gestionnaires de portefeuille"),
    aum: l("assets under management", "actif sous gestion"),
    vehicle: l("vehicle", "véhicule"),
    assetClass: l("asset class", "classe d’actifs"),
    risk: l("risk rating", "cote de risque"),
    asOf: l("as of", "au"),
    objective: l("objective", "objectif"),
  },
  docs: {
    kicker: l("documents", "documents"),
    title: l("read the details", "lire les détails"),
    firm: l("firm", "firme"),
    download: l("download", "télécharger"),
    types: {
      factsheet: l("factsheets", "fiches mensuelles"),
      "fund-facts": l("fund facts", "aperçus du fonds"),
      prospectus: l("offering documents", "documents de placement"),
      "annual-report": l("annual reports", "rapports annuels"),
      "interim-report": l("interim reports", "rapports intermédiaires"),
      mrfp: l("management reports of fund performance", "rapports de la direction sur le rendement du fonds"),
      commentary: l("commentaries", "commentaires"),
      presentation: l("presentations", "présentations"),
      esg: l("sustainability", "durabilité"),
      other: l("other", "autres"),
    } as Record<DocType, L>,
  },
  disclosure: {
    kicker: l("important information", "renseignements importants"),
    title: l("disclosure", "mentions importantes"),
    // regulatory texts: src/content/disclaimers.ts (compliance review)
    net: DISC.returnsNet,
    standard: DISC.fundStandard,
    index: DISC.benchmark,
    ftse: DISC.ftse,
    general: DISC.firm,
    provenance: l("Updated daily from Nymbus’ data platform", "Mis à jour quotidiennement à partir de la plateforme de données de Nymbus"),
    provenanceFactsheet: l("portfolio data from the monthly factsheet of", "données de portefeuille selon la fiche mensuelle de"),
    classShown: l("Performance shown", "Rendements présentés"),
    perfAsOf: l("performance as of", "rendements au"),
    navAsOf: l("net asset values as of", "valeurs liquidatives au"),
    aumAsOf: l("assets as of", "actif au"),
    sample: l(
      "The figures on this page are illustrative sample data used while the data platform is not connected. They are not the actual returns of the fund.",
      "Les chiffres de cette page sont des données fictives utilisées tant que la plateforme de données n’est pas branchée. Il ne s’agit pas des rendements réels du fonds.",
    ),
  },
  misc: {
    noData: l("figures will appear here once published", "les chiffres apparaîtront ici une fois publiés"),
    fund: l("fund", "fonds"),
    index: l("index", "indice"),
  },
} as const;

/** Pick the string of the current language. */
export const tr = (x: L | undefined | null, lang: "en" | "fr") => (x ? x[lang] || x.en : "");
